# @package _global_
defaults:
  - _self_
  - generate: default_generate

modeldir: ???
n_molecules: ???
batch_size: ???
max_n_atoms: ???

conditions: null

use_gpu: True
outputfile: null
view_molecules: False
workdir: null
remove_workdir: False
print_config: True

grid_distance_min: 0.7
grid_spacing: 0.05
temperature_term: 0.1
grid_batch_size: ${batch_size}

start_from_substructure: False

debug:
  run: False
  print_progress: False
  view_progress: False

settings:
  conditions:
    trajectory: ${conditions}

# hydra configuration
hydra:
    job:
        chdir: True
    # output paths for hydra logs
    run:
        dir: ${modeldir}

    # disable hydra config storage, since handled manually
    output_subdir: null

    help:
      app_name: schnetpack-gschnet G-SchNet Generate

      template: |-
        SchNetPack

        == Configuration groups ==
        Compose your configuration from those groups (db=mysql)

        $APP_CONFIG_GROUPS

        == Config ==
        This is the config generated for this run.
        You can change the config file to be loaded to a predefined one
        > generate.py --config-name=generate_molecules

        or your own:
        > generate.py --config-dir=./my_configs --config-name=my_config

        You can override everything, for example:
        > generate.py --config-name=generate_molecules outputfile=/path/to/out.db generate.batch_size=50 --help

        -------
        $CONFIG
        -------

        ${hydra.help.footer}